# Generated by Django 5.1.7 on 2025-03-19 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_customer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffeetype',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='coffee_images/'),
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
